openapi: 3.0.0
info:
  title: Admin API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/products:
    post:
      summary: Добавить товар
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: integer
                description:
                  type: string
      responses:
        "201":
          description: Товар добавлен
  /api/products/{id}:
    put:
      summary: Обновить товар
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Успешное обновление
    delete:
      summary: Удалить товар
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Успешное удаление

